-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           5.6.15-log - MySQL Community Server (GPL)
-- OS do Servidor:               Win32
-- HeidiSQL Versão:              9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura do banco de dados para projeto_tabela_periodica
CREATE DATABASE IF NOT EXISTS `projeto_tabela_periodica` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `projeto_tabela_periodica`;


-- Copiando estrutura para tabela projeto_tabela_periodica.elementos
CREATE TABLE IF NOT EXISTS `elementos` (
  `NRO_ATOMICO` int(3) NOT NULL,
  `SIMBOLO` varchar(3) DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `MASSA_ATOMICA` varchar(100) DEFAULT NULL,
  `IMAGEM` varchar(100) DEFAULT NULL,
  `FAMILIA` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`NRO_ATOMICO`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela projeto_tabela_periodica.elementos: 115 rows
/*!40000 ALTER TABLE `elementos` DISABLE KEYS */;
INSERT INTO `elementos` (`NRO_ATOMICO`, `SIMBOLO`, `NOME`, `MASSA_ATOMICA`, `IMAGEM`, `FAMILIA`) VALUES
	(1, 'H', 'HIDROGÊNIO', '1,00794', 'HIDROGENIO.JPG', 'NAO-METAL'),
	(2, 'He', 'HÉLIO', '4,002602', 'HELIO.JPG', 'GAS-NOBRE'),
	(3, 'Li', 'LÍTIO', '6,941', 'LITIO.JPG', 'METAL ALCALINO'),
	(4, 'Be', 'BERÍLIO', '9,012182', 'BERILIO.JPG', 'METAL ALCALINO TERROSO'),
	(5, 'B', 'BORO', '10,811', 'BORO.JPG', 'SEMI-METAL'),
	(6, 'C', 'CARBONO', '12,0107', 'CARBONO.JPG', 'NAO-METAL'),
	(7, 'N', 'NITROGÊNIO', '14,0067', 'NITROGENIO.JPG', 'NAO-METAL'),
	(8, 'O', 'OXIGÊNIO', '15,9994', 'OXIGENIO.JPG', 'NAO-METAL'),
	(9, 'F', 'FLÚOR', '18,9984032', 'FLUOR.JPG', 'HALOGENIOS'),
	(10, 'Ne', 'NEÔNIO', '20,1797', 'NEONIO.JPG', 'GAS-NOBRE'),
	(11, 'Na', 'SÓDIO ', '22,98976.....', 'SODIO.JPG', 'METAL ALCALINO'),
	(12, 'Mg', 'MAGNÉSIO', '24,305', 'MAGNESIO.JPG', 'METAL ALCALINO TERROSO'),
	(13, 'Al', 'ALUMÍNIO', '26,9315386', 'ALUMINIO.JPG', 'METAL REPRESENTATIVO'),
	(14, 'Si', 'SILÍCIO', '28,0855', 'SILICIO.JPG', 'SEMI-METAL'),
	(15, 'P', 'FÓSFORO', '30,973762', 'FOSFORO.JPG', 'SEMI-METAL'),
	(16, 'S', 'ENXOFRE', '32,065', 'ENXOFRE.JPG', 'SEMI-METAL'),
	(17, 'Cl', 'CLORO', '35,453', 'CLORO.JPG', 'HALOGENIOS'),
	(18, 'Ar', 'ARGÔNIO', '20,1797', 'ARGONIO.JPG', 'GAS-NOBRE'),
	(19, 'K', 'POTASSIO', '39,0983', 'POTASSIO.JPG', 'METAL ALCALINO'),
	(20, 'Ca', 'CÁLCIO', '40,078', 'CALCIO.JPG', 'METAL ALCALINO TERROSO'),
	(21, 'Sc', 'ESCÃNDIO', '44,955912', 'ESCANDIO.JPG', 'METAL TRANSIÇÃO'),
	(22, 'Ti', 'TITÂNIO', '47,867', 'TITANIO.JPG', 'METAL TRANSIÇÃO'),
	(23, 'V', 'VANÁDIO', '50,9415', 'VANADIO.JPG', 'METAL TRANSIÇÃO'),
	(24, 'Cr', 'CRÔMO', '51,9961', 'CROMO.JPG', 'METAL TRANSIÇÃO'),
	(25, 'Mn', 'MANGANÊS', '54,938045', 'MANGANES.JPG', 'METAL TRANSIÇÃO'),
	(26, 'Fe', 'FERRO', '55,845', 'FERRO.JPG', 'METAL TRANSIÇÃO'),
	(27, 'Co', 'COBALTO', '58,933195', 'COBALTO.JPG', 'METAL TRANSIÇÃO'),
	(28, 'Ni', 'NÍQUEL', '58,6934', 'NIQUEL.JPG', 'METAL TRANSIÇÃO'),
	(29, 'Cu', 'COBRE', '63,546', 'COBRE.JPG', 'METAL TRANSIÇÃO'),
	(30, 'Zn', 'ZINCO', '65,38', 'ZINCO.JPG', 'METAL TRANSIÇÃO'),
	(31, 'Ga', 'GÁLIO', '69,723', 'GALIO.JPG', 'METAL REPRESENTATIVO'),
	(32, 'Ge', 'GERMÃNIO', '72,63', 'GERMANIO.JPG', 'SEMI-METAL'),
	(33, 'As', 'ARSÊNIO', '74,9216', 'ARSENIO.JPG', 'SEMI-METAL'),
	(34, 'Se', 'SELÊNIO', '78,96', 'SELENIO.JPG', 'NAO-METAL'),
	(35, 'Br', 'BROMO', '79,904', 'BROMO.JPG', 'HALOGÊNIOS'),
	(36, 'Kr', 'CRIPITÓNIO', '83,798', 'CRIPITONIO.JPG', 'GAS-NOBRE'),
	(37, 'Rb', 'RUBÍDIO', '85,4678', 'RUBIDIO.JPG', 'METAL ALCALINO'),
	(38, 'Sr', 'ESTRÔNCIO', '87,62', 'ESTRONCIO.JPG', 'METAL ALCALINO TERROSO'),
	(39, 'Y', 'ÍTRIO', '88,90585', 'ITRIO.JPG', 'METAL TRANSIÇÃO'),
	(40, 'Zr', 'ZIRCÔNIO', '91,224', 'ZIRCONIO.JPG', 'METAL TRANSIÇÃO'),
	(41, 'Nb', 'NIÓBIO', '92,90638', 'NIOBIO.JPG', 'METAL TRANSIÇÃO'),
	(42, 'Mo', 'MOLIBDÊNIO', '95,96', 'MOLIBDENIO.JPG', 'METAL TRANSIÇÃO'),
	(43, 'Tc', 'TECNÉCIO', '98', 'TECNECIO.JPG', 'METAL TRANSIÇÃO'),
	(44, 'Ru', 'RUTÊNIO', '101,07', 'RUTENIO.JPG', 'METAL TRANSIÇÃO'),
	(45, 'Rh', 'RÓDIO', '102,9055', 'RODIO.JPG', 'METAL TRANSIÇÃO'),
	(46, 'Pd', 'PALÁDIO', '106,42', 'PALADIO.JPG', 'METAL TRANSIÇÃO'),
	(47, 'Ag', 'PRATA', '107,8682', 'PRATA.JPG', 'METAL TRANSIÇÃO'),
	(48, 'Cd', 'CÁDMIO', '112,411', 'CADMIO.JPG', 'METAL TRANSIÇÃO'),
	(49, 'In', 'ÍNDIO', '114,818', 'INDIO.JPG', 'METAL REPRESENTATIVO'),
	(50, 'Sn', 'ESTANHO', '118,71', 'ESTANHO.JPG', 'METAL REPRESENTATIVO'),
	(51, 'Sb', 'ANTIMÔNIO', '121,76', 'ANTIMONIO.JPG', 'SEMI-METAL'),
	(52, 'Te', 'TELÚRIO', '127,6', 'TELURIO.JPG', 'SEMI-METAL'),
	(53, 'I', 'IODO', '126,90447', 'IODO.JPG', 'HALOGÊNIOS'),
	(54, 'Xe', 'XENÔNIO', '131,293', 'XENONIO.JPG', 'GAS-NOBRE'),
	(55, 'Cs', 'CÉSIO', '132,9054...', 'CESIO.JPG', 'METAL ALCALINO'),
	(56, 'Ba', 'BÁRIO', '137,327', 'BARIO.JPG', 'METAL ALCALINO TERROSO'),
	(57, 'La', 'LANTÂNIO', '138,90547', 'LANTANIO.JPG', 'LANTANÍDEOS'),
	(58, 'Ce', 'CÉRIO', '140,116', 'CERIO.JPG', 'LANTANÍDEOS'),
	(59, 'Pr', 'PRASEODÍMIO', '140,90765', 'PRASEODIMIO.JPG', 'LANTANÍDEOS'),
	(60, 'Nd', 'NEODÍMIO', '144,242', 'NEODIMIO.JPG', 'LANTANÍDEOS'),
	(61, 'Pm', 'PROMÉCIO', '(145)', 'PROMECIO.JPG', 'LANTANÍDEOS'),
	(62, 'Sm', 'SAMÁRIO', '150,36', 'SAMARIO.JPG', 'LANTANÍDEOS'),
	(63, 'Eu', 'EURÓPIO', '151,964', 'EUROPIO.JPG', 'LANTANÍDEOS'),
	(64, 'Gd', 'GADOLÍNIO', '157,25', 'GADOLINIO.JPG', 'LANTANÍDEOS'),
	(65, 'Tb', 'TÉRBIO', '158,92535', 'TERBIO.JPG', 'LANTANÍDEOS'),
	(66, 'Dy', 'DISPRÓSIO', '162,5', 'DISPROSIO.JPG', 'LANTANÍDEOS'),
	(67, 'Ho', 'HÓLMIO', '164,93032', 'HOLMIO.JPG', 'LANTANÍDEOS'),
	(68, 'Er', 'ÉRBIO', '167,259', 'ERBIO.JPG', 'LANTANÍDEOS'),
	(69, 'Tm', 'TÚLIO', '168,93421', 'TULIO.JPG', 'LANTANÍDEOS'),
	(70, 'Yb', 'ITÉRBIO', '173,054', 'ITERBIO.JPG', 'LANTANÍDEOS'),
	(71, 'Lu', 'LUTÉCIO', '174,9668', 'LUTECIO.JPG', 'LANTANÍDEOS'),
	(72, 'Hf', 'HÁFNIO', '178,49', 'HAFNIO.JPG', 'METAL TRANSIÇÃO'),
	(73, 'Ta', 'TÂNTALO', '180,94788', 'TANTALO.JPG', 'METAL TRANSIÇÃO'),
	(74, 'W', 'TUNGSTÊNIO', '183,84', 'TUNGSTENIO.JPG', 'METAL TRANSIÇÃO'),
	(75, 'Re', 'RÊNIO', '186,207', 'RENIO.JPG', 'METAL TRANSIÇÃO'),
	(76, 'Os', 'ÓSMIO', '190,23', 'OSMIO.JPG', 'METAL TRANSIÇÃO'),
	(77, 'Ir', 'IRÍDIO', '192,217', 'IRIDIO.JPG', 'METAL TRANSIÇÃO'),
	(78, 'Pt', 'PLATINA', '195,084', 'PLATINA.JPG', 'METAL TRANSIÇÃO'),
	(79, 'Au', 'OURO', '196,966569', 'OURO.JPG', 'METAL TRANSIÇÃO'),
	(80, 'Hg', 'MERCÚRIO', '200,59', 'MERCURIO.JPG', 'METAL TRANSIÇÃO'),
	(81, 'Tl', 'TÁLIO', '204,3833', 'TALIO.JPG', 'METAL REPRESENTATIVO'),
	(82, 'Pb', 'CHUMBO', '207,2', 'CHUMBO.JPG', 'METAL REPRESENTATIVO'),
	(83, 'Bi', 'BISMUTO', '208,9804', 'BISMUTO.JPG', 'METAL REPRESENTATIVO'),
	(84, 'Po', 'POLÔNIO', '(209)', 'POLONIO.JPG', 'SEMI-METAL'),
	(85, 'At', 'ASTATO', '(210)', 'ASTATO.JPG', 'HALOGÊNIOS'),
	(86, 'Rn', 'RADÔNIO', '(222)', 'RADONIO.JPG', 'GAS-NOBRE'),
	(87, 'Fr', 'FRÂNCIO', '(223)', 'FRANCIO.JPG', 'METAL ALCALINO'),
	(88, 'Ra', 'RÁDIO', '(226)', 'RADIO.JPG', 'METAL ALCALINO TERROSO'),
	(89, 'Ac', 'ACTÍNIO', '(227)', 'ACTINIO.JPG', 'ACTINÍDEOS'),
	(90, 'Th', 'TÓRIO', '232,03806', 'TORIO.JPG', 'ACTINÍDEOS'),
	(91, 'Pa', 'PROTACTÍNIO', '231,03588', 'PROTACTINIO.JPG', 'ACTINÍDEOS'),
	(92, 'U', 'URÂNIO', '238,02891', 'URANIO.JPG', 'ACTINÍDEOS'),
	(93, 'Np', 'NEPTÚNIO', '(237)', 'NEPTUNIO.JPG', 'ACTINÍDEOS'),
	(94, 'Pu', 'PLUTÔNIO', '(244)', 'PLUTONIO.JPG', 'ACTINÍDEOS'),
	(95, 'AM', 'AMERÍCIO', '(243)', 'AMERICIO.JPG', 'ACTINÍDEOS'),
	(96, 'Cm', 'CÚRIO', '(247)', 'CURIO.JPG', 'ACTINÍDEOS'),
	(97, 'Bk', 'BERQUÉLIO', '(247)', 'BERQUELIO.JPG', 'ACTINÍDEOS'),
	(98, 'Cf', 'CALIFÓRNIO', '(251)', 'CALIFORNIO.JPG', 'ACTINÍDEOS'),
	(99, 'Es', 'EINSTÊNIO', '(252)', 'EINSTENIO.JPG', 'ACTINÍDEOS'),
	(100, 'Fm', 'FÉRMIO', '(257)', 'FERMIO.JPG', 'ACTINÍDEOS'),
	(101, 'Md', 'MENDELÉVIO', '(258)', 'MENDELEVIO.JPG', 'ACTINÍDEOS'),
	(102, 'No', 'NOBÉLIO', '(259)', 'NOBELIO.JPG', 'ACTINÍDEOS'),
	(103, 'Lr', 'LAURÊNCIO', '(262)', 'LAURENCIO.JPG', 'ACTINÍDEOS'),
	(104, 'Rf', 'RUTHERFÓRDIO', '(267)', 'RUTHERFORDIO.JPG', 'METAL TRANSIÇÃO'),
	(105, 'Db', 'DÚBNIO', '(268)', 'DUBNIO.JPG', 'METAL TRANSIÇÃO'),
	(106, 'Sg', 'SEABÓRGIO', '(271)', 'SEABORGIO.JPG', 'METAL TRANSIÇÃO'),
	(107, 'Bh', 'BÓHRIO', '(272)', 'BOHRIO.JPG', 'METAL TRANSIÇÃO'),
	(108, 'Hs', 'HÁSSIO', '(270)', 'HASSIO.JPG', 'METAL TRANSIÇÃO'),
	(109, 'Mt', 'MEITNÉRIO', '(276)', 'MEITNERIO.JPG', 'METAL TRANSIÇÃO'),
	(110, 'Ds', 'DARMSTÁDIO', '(281)', 'DARMSTADIO.JPG', 'METAL  TRANSIÇÃO'),
	(111, 'Rg', 'ROENTGÊNIO', '(280)', 'ROENTGENIO.JPG', 'METAL TRANSIÇÃO'),
	(112, 'Cn', 'COPERNÍCIO', '(285)', 'COPERNICIO.JPG', 'METAL TRANSIÇÃO'),
	(113, 'Uut', 'UNUNTRIO', '(284)', 'UNUNTRIO.JPG', 'METAL REPRESENTATIVO'),
	(114, 'Uuq', 'UNUNQUÁDIO', '(289)', 'UNUNQUADIO.JPG', 'METAL REPRESENTATIVO'),
	(115, 'Uup', 'UNUNPENTIO', '(288)', 'UNUNPENTIO.JPG', 'METAL REPRESENTATIVO'),
	(116, 'Uuh', 'UNUNHÉXIO', '(293)', 'UNUNHEXIO.JPG', 'METAL REPRESENTATIVO'),
	(117, 'Uus', 'UNUNSÉPTIO', '(294)', 'UNUNSEPTIO.JPG', 'HALOGÊNIOS'),
	(118, 'Uuo', 'UNUNÓCTIO', '(294)', 'UNUNOCTIO.JPG', 'GAS-NOBRE');
/*!40000 ALTER TABLE `elementos` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
